splash = false

preload = ~/Pictures/gruvbox-wallpapers/wallpapers/pixelart/gruvbox_image31.png
preload = ~/Pictures/GlassPhantoms_smoothed_gruvbox.png

wallpaper = HDMI-A-1,~/Pictures/gruvbox-wallpapers/wallpapers/pixelart/gruvbox_image31.png
wallpaper = DP-3,~/Pictures/GlassPhantoms_smoothed_gruvbox.png
